# Generated by Django 4.2.3 on 2023-08-10 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Наименование')),
                ('measure', models.CharField(max_length=10, verbose_name='Ед. измерения')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена со скидкой')),
                ('manufacturer', models.CharField(max_length=300, verbose_name='Производитель')),
                ('expiration_date', models.DateField(verbose_name='Срок годности')),
                ('price_without_discount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена без скидкой')),
            ],
        ),
    ]
