# Generated by Django 4.2.3 on 2023-09-03 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(default='01/01/2025', verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(default='', max_length=300, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='measure',
            field=models.CharField(default='', max_length=10, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена со скидкой'),
        ),
    ]
