# Generated by Django 4.2.3 on 2023-09-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicine', '0003_alter_medicine_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='expiration_date',
            field=models.DateField(default=None, null=True, verbose_name='Срок годности'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='manufacturer',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='measure',
            field=models.CharField(default='', max_length=10, null=True, verbose_name='Ед. измерения'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='name',
            field=models.CharField(max_length=300, null=True, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='medicine',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
